[package]
name = "models"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
strum.workspace = true
sqlx.workspace = true
eyre.workspace = true
serde_json.workspace = true
