[package]
name = "maimai-db"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
models = { path = "../models" }
